// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Review struct {
	Body    string   `json:"body"`
	Author  *User    `json:"author"`
	Product *Product `json:"product"`
}
