apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-server
  labels:
    app: accounts-server
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: accounts-server
  template:
    metadata:
      labels:
        app: accounts-server
    spec:
      containers:
      - name: accounts-server
        image: accounts-server-image
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080