# apollo server
# - reload
# - jwt verify
# apollo operator

# schema registry
# topic with replication
# replication for offsets
# topic browser
# dashboard / alerting rules / servicemonitor
# minio
# minio kafka sync
# jaeger
# jwt auth

local_resource(
    name="infra services",
    cmd="helmfile template | grep -v 'namespace: default' > services.yaml",
    deps=["helmfile.yaml"],
)
k8s_yaml('services.yaml')
k8s_resource('kafka', resource_deps=['kafka-zookeeper'])

include('./apollo-server/Tiltfile')
