# kafka
# zookeeper
# schema registry
# topic with replication
# replication for offsets
# topic browser
# dashboard / alerting rules / servicemonitor
# apollo server
# - reload
# - jwt verify
# apollo operator
# minio
# minio kafka sync
# jaeger
# jwt auth

allow_k8s_contexts(os. geten("ALLOW_TILT_CONTEXT"))

local_resource(
    name="infra services",
    cmd="helmfile template > services.yaml",
    deps=["helmfile.yaml"],
)

k8s_yaml('services.yaml')
