
k8s_yaml('kubernetes.yaml')

k8s_resource('reviews-server', port_forwards=['127.0.0.1:8003:8080'])

docker_build(
  ref='reviews-server-image',
  context='.',
  ignore=[
    'vendor',
    'kubernetes.yaml',
  ],
)
