apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-server
  labels:
    app: apollo-server
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apollo-server
  template:
    metadata:
      labels:
        app: apollo-server
    spec:
      containers:
      - name: apollo-server
        image: apollo-server-image
        ports:
          - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: apollo
spec:
  selector:
    app: apollo-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000