apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-server
  labels:
    app: products-server
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: products-server
  template:
    metadata:
      labels:
        app: products-server
    spec:
      containers:
      - name: products-server
        image: products-server-image
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080